### ISSUE TITLE
Add support for ISaveChangesInterceptor

### ISSUE THREAD

**Issue by mcattle** [artiomchi/FlexLabs.Upsert#102]
I'll add my voice to everyone else that this is a great and much needed library.

In my data service, I'm using a class that implements the [ISaveChangesInterceptor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.isavechangesinterceptor?view=efcore-5.0) interface in order to auto-populate audit fields on `Context.SaveChanges()` and `Context.SaveChangesAsync()` (setting `AuditCreated*` fields on insert, setting 'AuditUpdated*` fields on update, and resetting changes in the 'AuditCreated*` fields on update), so that developers that use the context don't have to remember to do that with every command.

Would it be possible to find and hook into any registered RF interceptor classes when building the database command in order to auto-populate (or remove) these fields in the process of generating the command?

My workaround for the time being is to set these fields manually whenever doing an `Upsert`, but if the interceptors can be used, this would ensure that it would happen automatically and no Upsert would accidently get overlooked.

**Comment by adambajguz** [comment]
I have a similar problem. What I need are Upsert and TryAdd operations that work when SaveChanges(Async) is called. I wish DbContext has native support for these operations :|.

TryAdd is obvious - it should result in setting entity state to Detached, but I don't know how should Upsert behave. Suppose we have some logic in SavingChanges(Async) inside save interceptor, which modifies entity differently on add and update; when we add an entity but it will actually result in update this will mess up entity state. Probably SavedChanges(Async) is the least problematic because SQL could return whether the entity was added or updated, then we can e.g. fix aggregate root domain events by removing added and inserting updated event.

**Comment by artiomchi** [comment]
Hey @mcattle, @adambajguz,

Thanks for your kind words and support!

Unfortunately, I don't think I'd be able to leverage the save changes interceptors, since the updates are done completely differently with this library.  This library just takes the input objects and builds a SQL statement to insert them. The save changes interceptor on the other hand gives you access to the dbContext event data, and you look at which objects are in the change tracker (from what I've seen at least). Since I'm not using (or affecting) the change tracker in the first place, the ISaveChangesInterceptor would be of no use.

Besides, we wouldn't even be able to know whether an object is created or updated before the query runs. 

I know this is not the response you were expecting. If you do have any suggestions or ideas, I'd be happy to look into this more, but at the moment I don't think it would work

**Comment by mcattle** [comment]
I think that to make this work, you'd have to create your own `DbContextEventData` instance with a new `Context` instance that contains two changed `EntityEntry` objects, in both the created (Upsert) and updated (WhenMatched) states, and then manually pass it through the registered interceptor chain.  The results would then be extracted to build the underlying query.  I imagine for performance this would all be short-circuited if the `DBContext` doesn't have any `SaveInterceptors` registered.
