### ISSUE TITLE
Spelling error in InvalidMatchColumnsException, requested exception message improvement

### ISSUE THREAD

**Issue by paultobey** [artiomchi/FlexLabs.Upsert#157]
Just hit an invalid match exception 6.0.2. Here's the message:

FlexLabs.EntityFrameworkCore.Upsert.InvalidMatchColumnsException: 'Using autogenerated / identity keys as the upsert match excession is not supported. Pick a non generated unique key. See https://go.flexlabs.org/upsert.identitykeymatch for more details'

I assume "excession" should be "expression".

While working on this, please provide more-detailed information on developer fixes ("When using PostgreSQL, the UpdateIf() expression must <whatever>." or "When using SQL Server, the On() expression must <whatever2>") Pointing to a page is fine but the detailed information needed to fix the problem seems to be available to the exception (since it was thrown because of some violation!), so it should take advantage of that helping fix the problem. In this case, you know whether the problem is autogenerated or identity, so help us understand what we did wrong!

In my case, I'm choosing one column, NOT auto-generated, of a composite key. That seems like it should be fine.

```
Columns = {id, company_id, sat_id, data_type, data}
Key = { id NOT NULL auto-generated, company_id NOT NULL }
UpdateIf(item => new { item.company_id, item.sat_id, item.data_type });

```
-OR-
```
On(item =>  new { item.company_id, item.sat_id, item.data_type });
```

Not urgent (obviously), but a quality improvement.

**Comment by artiomchi** [comment]
Hi @paultobey, good catch on the typo there!

Unfortunately, writing the code fixes ends up more complicated.. It's not always as obvious why EF thinks that the column might generate new values on insert (instead of using supplied values), hence the exception messages are a bit vague. And I provided the links for that, since I thought it'd be easier to have a page describing the details of an error, and the cases it might be caused, instead of trying to read an in-depth explanation inside the app error logs :)
