### ISSUE TITLE
InvalidMatchColumndException but not autogenerated keys in sqlite

### ISSUE THREAD

**Issue by Lauchi** [artiomchi/FlexLabs.Upsert#31]
Hi,

first and foremost: Cool library, that was exactly what I was searching for 👍 

I am having a very simple database with sqlite and EF Core and want to use Upsert like this:

`await _context.Querries.Upsert(new QueryDbo
                {
                    Type = query.GetType().Name,
                    Payload = _converter.Serialize(query)
                })
                .RunAsync();`

The Type is marked as [key] in the dbContext so I should not need the .On notation. I also tried to use the .On and .When with many combinations, but this just does not work. I also read the sqlite guide and added the references, but the problem still persists. Am I doing something wrong here?

I have the solution on a branch if you want to have a closer look:
this is my usage: https://github.com/Lauchi/EventStoreFacade/blob/upsertTest/Adapters.Framework.Queries/QueryRepository.cs
this is the context:
https://github.com/Lauchi/EventStoreFacade/blob/upsertTest/Adapters.Framework.Queries/QueryStorageContext.cs
this is some tests, that throw the error:
https://github.com/Lauchi/EventStoreFacade/blob/upsertTest/Adapters.Framework.Queries.UnitTests/QueryRepositoryTest.cs

**Comment by rajivkukreja** [comment]
@artiomchi - thanks for doing this .. its incredibly useful. 

@Lauchi - I have the same issue on a very simple postgres table which has an Id column (PK) and is marked with [Key] on the dbcontext object. You mentioned that you have a solution on a branch - can you please point me to it? 

Thanks very much

**Comment by Lauchi** [comment]
@rajivkukreja 
I do not have a solution, I only have the problem in a branch ;)

**Comment by artiomchi** [comment]
Hey guys, sorry it took me so long to reply.
So this is somewhat interesting, and possibly shows a difference in how EF Core works.

Taking the example from @rajivkukreja as a starting point - you have a table with a string key property. Since you haven't modified the key definition, it's initialised with the default settings, including the fact that it's marked as database generated by default.

The interesting thing about Guid and string keys (from what I just tested) is that they're marked as DB generated by default, and if a value is not provided - they'll have one auto generated (with the string key - it'll get a new guid as a value). 

The upsert library doesn't let you join on database generated values, for reasons I listed here: https://go.flexlabs.org/upsert.identitykeymatch

In your case, if you want a table with a string key that's provided from code, you should decorate it like this in your table class:

```csharp
[Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
public string ID { get; set; }
```

**Comment by Lauchi** [comment]
Thanks for the tip, this is working for me now!
