### ISSUE TITLE
Could not install package 'FlexLabs.EntityFrameworkCore.Upsert 2.1.2'. 

### ISSUE THREAD

**Issue by beta2k** [artiomchi/FlexLabs.Upsert#66]
When trying to install the package into my C# project, I get the following error

> You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework

What am I doing wrong?

**Comment by artiomchi** [comment]
Hi @beta2k 

This package is built against .NET Standard 2.0, so the minimal level of .NET framework it's compatible is .NET 4.6.1, as per the [.NET Standard docs](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

That's why you're getting the error message above.
A the moment that means you might have to upgrade your project to target a newer .NET framework version
