### ISSUE TITLE
Return upserted entity

### ISSUE THREAD

**Issue by jjxtra** [artiomchi/FlexLabs.Upsert#70]
Is it possible to return the upserted entity? Right now it looks like the internals just execute a sql command. There could be a data reader call in the same sql query that returns updated values, which would save a second query lookup.

If one needs the updated values from the db, the upsert is no better than a FirstOrDefault, followed by either an update of the existing entity or an insert of a new entity.

**Comment by artiomchi** [comment]
This is already planned, but wasn't implemented yet due to some complications. This is currently tracked in #29, so I'll be closing this as a duplicate

> If one needs the updated values from the db, the upsert is no better than a FirstOrDefault, followed by either an update of the existing entity or an insert of a new entity.

Actually no, the benefit of the upsert is that it is an atomic operation. If you ran an `.FirstOrDefault()` which returned a null, and before you could create a new entry a different process/thread created it, you'd get an exception. Running `.Upsert()` on the other hand, ensures that the check and the insert are done as part of a single operation.
