### ISSUE TITLE
Upsert on conflict 

### ISSUE THREAD

**Issue by odirleiborgert** [artiomchi/FlexLabs.Upsert#75]
The error occurs when in the same range I add 2 identical records.

> ON CONFLICT DO UPDATE command cannot affect row a second time

```
await _context.Contact.UpsertRange(listContacts)
    .On(v => new { v.phone })
    .WhenMatched(v => new Contact
    {
        updated_at = DateTime.UtcNow
    })
    .RunAsync();
```

**Comment by artiomchi** [comment]
Hi @odirleiborgert 

Indeed, this is thrown because you add two records with the same value that you considered unique. You would end up with the same issue if you created the SQL query yourself and tried to upsert your dataset.

When you run the upsert query, it is the developer's responsibility to ensure that the dataset you try to upsert doesn't have any duplicate keys. There is no way for the library to know how to handle it otherwise, since it depends on your business logic.

You could accomplish that with a group by your match column, in your example - `phone`, picking only one record from each group, and sending just these to the upsert query.
