### ISSUE TITLE
Be able to determine if Upsert resulted in INSERT or UPDATE, and maybe even new state of the entity

### ISSUE THREAD

**Issue by quetzalcoatl** [artiomchi/FlexLabs.Upsert#78]
This is an idea for improvement.

Currently, `await foo.Upsert(entity).....RunAsync()` returns "number of rows affected", that doesn't let us know if the record already existed. In some use cases, that's an important information., or at least can save us from doing a preceding query just to check if it existed.

For PostgreSQL that's pretty simple, citing after: https://stackoverflow.com/a/40880200/717732

```
INSERT INTO tbl(id, col)
VALUES (1,11), (2,22)
ON     CONFLICT (id) DO UPDATE
SET    col = EXCLUDED.col
RETURNING *, (xmax = 0) AS inserted;    // <------ HERE
```

The `xmax as inserted` returns this information as an additional column in the record set. By the way, this `returning *` also means that we actually can get the most-recent state of the entity at the same time. This could also be useful if we want to read the new entity back, saves us from one query after the operation.

I've checked Sql Server as well, and according to: https://www.flexlabs.org/2018/02/adding-upsert-support-for-entity-framework-core it seems pretty easy as well, and that dedicated MERGE command supports "output clause" (https://docs.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql?view=sql-server-ver15) that is a select-list, so it's possible to return the new state of the entity as well, and special `$action` column available in the output-clause allows to determine the inserted/updated for given row.

I've no checked other databases, sorry. At least it seems easy on those two :)

**Comment by artiomchi** [comment]
Hey there, this is absolutely true, and would be a great improvement. Unfortunately, I haven't had time to try come up with the best way to handle this, as I work on this project in my off-time, and I end up with massive periods of inactivity. This issue is basically a duplicate of #29, and has been raised several times in the past. I'll close this issue, but you can subscribe to the other issue to see when this gets implemented.

Of course, I'm always happy to receive some help, so if you can come up with a good implementation we can always try and merge it in
