### ISSUE TITLE
Navigation property is null after insert

### ISSUE THREAD

**Issue by AndresLuga** [artiomchi/FlexLabs.Upsert#87]
Hi,

The example below leaves the Company null in the database. I feel I'm missing something simple. [Sample project:](https://github.com/Lux44/UpsertQuestion)

```
public class SummaryCard : BaseEntity

    {        
        public Company Company { get; set; }

        public string Number { get; set; }

    }

var summaryCard = new SummaryCard { Number = "1", Company = company, State = State.Active };

await db.SummaryCards.Upsert(summaryCard)
```

**Comment by GioviQ** [comment]
I think Upsert is working only for a single entity.

**Comment by artiomchi** [comment]
Hi @AndresLuga 

That is correct, this library doesn't support navigation properties or complex objects, since it wouldn't be possible (in most cases) to translate this to a single SQL statement.

If the company if your case is a foreign key, you could expose the foreign key property in your object (`CompanyId` ?), and set that in the upsert statement instead. That is assuming the company already exists in the database. If it doesn't, you'd have to ensure it exists first
