### ISSUE TITLE
GUID Primary Key is not generated on Upsert

### ISSUE THREAD

**Issue by Hoffs** [artiomchi/FlexLabs.Upsert#93]
I encountered an issue where GUID PK generated value is not actually generated when upserting with match. I tested in SQLite and it fails with `SQLite Error 19: 'NOT NULL constraint failed: GuidKeysAutoGen.ID'.`. 

I modified one of the test cases in `BasicTest.cs` and reused `GuidKeyAutoGen` table (added unique constraint on `Name` column) and this is sufficient to reproduce:
```csharp
var newItem = new GuidKeyAutoGen
{
    // ID = Guid.NewGuid(),
    Name = "test",
};

dbContext.GuidKeysAutoGen.Upsert(newItem).On(x => new { x.Name })
.Run();
```

As seen in the `Upsert_EFCore_KeyAutoGen` test case, just adding the entry and saving auto generates the key, but when inserting using upsert it just fails with a NULL error. So is this expected behavior and it should be generated manually when using `Upsert`?

**Comment by dennisroche** [comment]
Sorry to side track this issue, but found a similar/related issue to GUID Primary Keys not working with `Upsert`. 

We create our Primary Key in the app rather than generated by the database as it can be helpful to know the PK without having to query afterwards for subsequent actions. 

What I found after debugging into `Upsert` it was filtering our `[Key]` from the generated SQL and giving a null value in column "id" violates not-null constraint` **because** it thought it was autogenerated despite already having a value (which was sufficient to EF Core for work normally). 

The fix was simply be more explicit. 

```
public abstract class Entity<TIdentifier> where TIdentifier : struct, IEquatable<TIdentifier>
{
        [Key]
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public TIdentifier Id { get; protected set; }
}
```

Adding this didn't require a new migration so it must be additional meta data used in `entityType.GetProperties()`

**Comment by dennisroche** [comment]
@Hoffs perhaps the inverse is required for you, e.g. you might need to set `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` in our model.

**Comment by artiomchi** [comment]
@Hoffs - that's correct - when you're upserting entries with a Guid column, you'll have to generate your own Guids. There were some discussions about this in the past, and in short - there's no simple and easy way to know whether you're trying to genuinely insert a `Guid.Empty` into the database, or if you forgot to populate it. Also, like @dennisroche stated, it puts you in control of the value inserted, in case you might need it later

**Comment by artiomchi** [comment]
@dennisroche That is also correct - if you have a Guid identity key, the solution is to mark it as non auto generated, and then populate your own values on insert
